languageCode = "zh"
languageName = "中文"
languageDirection = "ltr"
weight = 1

title = "marsevilspirit's blog"
# copyright = "Copy, _right?_ :thinking_face:"

[params]
dateFormat = "2006年 1月 2日"

# mainSections = ["section1", "section2"]
description = "Marsevilspirit 的技术博客, 分享软件开发、Neovim 配置与网络安全心得。"

[params.author]
name = "marsevilspirit"
image = "img/author.png"
headline = "软件工程师"
bio = "用人类的逻辑去写出诗一样优雅的代码，这是我活着的意义。"
links = [
    { github = "https://github.com/marsevilspirit" },
    { mastodon = "https://infosec.exchange/@marsevilspirit" },
    { email = "mailto:marsevilspirit@gmail.com" },
    { rss = "https://www.marsevilspirit.com/zh/index.xml" },
]
# links = [
#   { email = "mailto:hello@your_domain.com" },
#   { link = "https://link-to-some-website.com/" },
#   { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
#   { apple = "https://www.apple.com" },
#   { blogger = "https://username.blogspot.com/" },
#   { codepen = "https://codepen.io/username" },
#   { dev = "https://dev.to/username" },
#   { discord = "https://discord.gg/invitecode" },
#   { dribbble = "https://dribbble.com/username" },
#   { facebook = "https://facebook.com/username" },
#   { flickr = "https://www.flickr.com/photos/username/" },
#   { foursquare = "https://foursquare.com/username" },
#   { github = "https://github.com/username" },
#   { gitlab = "https://gitlab.com/username" },
#   { google = "https://www.google.com/" },
#   { google-scholar = "https://scholar.google.com/citations?user=user-id" },
#   { hashnode = "https://username.hashnode.dev" },
#   { instagram = "https://instagram.com/username" },
#   { keybase = "https://keybase.io/username" },
#   { kickstarter = "https://www.kickstarter.com/profile/username" },
#   { kofi = "https://ko-fi.com/username" },
#   { lastfm = "https://lastfm.com/user/username" },
#   { linkedin = "https://linkedin.com/in/username" },
#   { mastodon = "https://mastodon.instance/@username" },
#   { medium = "https://medium.com/username" },
#   { mendeley = "https://www.mendeley.com/" },
#   { microsoft = "https://www.microsoft.com/" },
#   { orcid = "https://orcid.org/userid" },
#   { patreon = "https://www.patreon.com/username" },
#   { pinterest = "https://pinterest.com/username" },
#   { reddit = "https://reddit.com/user/username" },
#   { researchgate = "https://www.researchgate.net/profile/username" },
#   { slack = "https://workspace.url/team/userid" },
#   { snapchat = "https://snapchat.com/add/username" },
#   { soundcloud = "https://soundcloud.com/username" },
#   { stack-overflow = "https://stackoverflow.com/users/userid/username" },
#   { steam = "https://steamcommunity.com/profiles/userid" },
#   { telegram = "https://t.me/username" },
#   { threads = "https://threads.net/@username" },
#   { tiktok = "https://tiktok.com/@username" },
#   { tumblr = "https://username.tumblr.com" },
#   { twitch = "https://twitch.tv/username" },
#   { whatsapp = "https://wa.me/phone-number" },
#   { x-twitter = "https://twitter.com/username" },
#   { youtube = "https://youtube.com/username" },
#   { xing = "https://xing.com/profile/username" },
# ]
